version: ~> 1.0
env:
  global:
    - REPO_DIR=httpstan
    - BUILD_COMMIT=2.3.0
    - BUILD_DEPENDS=""
    # test dependencies from the [tool.poetry.dev-dependencies] section in pyproject.toml
    - TEST_DEPENDS="pytest~=5.4 pytest-cov~=2.8 pytest-asyncio<0.11,>=0.10 apispec[yaml,validation]~=3.1"
    - MB_ML_VER=2014
    - DOCKER_TEST_IMAGE=multibuild/xenial_x86_64

language: python
python: 3.7
os: linux
dist: xenial
services: docker

jobs:
  - os: linux
    env:
      - MB_PYTHON_VERSION=3.7
  - os: osx
    osx_image: xcode11.3
    language: objective-c
    env:
      - MB_PYTHON_VERSION=3.7
  - os: linux
    env:
      - MB_PYTHON_VERSION=3.8
  - os: osx
    osx_image: xcode11.3
    language: objective-c
    env:
      - MB_PYTHON_VERSION=3.8
  - os: linux
    env:
      - MB_PYTHON_VERSION=3.9
  - os: osx
    osx_image: xcode11.3
    language: objective-c
    env:
      - MB_PYTHON_VERSION=3.9
before_install:
  - source multibuild/common_utils.sh
  - source multibuild/travis_steps.sh
  - before_install

install:
  # get and clean source
  - clean_code $REPO_DIR $BUILD_COMMIT
  # use travis_wait to bypass 10 minute timeout on osx. Running delocate takes > 10m.
  - |
    if [ ${TRAVIS_OS_NAME} = "osx" ]; then
      travis_wait 60 build_wheel $REPO_DIR
    else
      build_wheel $REPO_DIR
    fi

script:
  - install_run

after_success:
  # PYPI_TOKEN is a secure variable set via the travis-ci.com website
  - |
    if [[ $TRAVIS_PULL_REQUEST == "false" ]]; then
      python3 -m pip install twine
      python3 -m twine upload --skip-existing -u __token__ -p "$PYPI_TOKEN" ${TRAVIS_BUILD_DIR}/wheelhouse/*.whl
    else
      echo "This build is connected to a pull request. Not uploading to PyPI."
    fi
