version: ~> 1.0
env:
  global:
    - REPO_DIR=httpstan
    - BUILD_COMMIT=1.1.2
    - BUILD_DEPENDS="Cython"
    # test dependencies from the [tool.poetry.dev-dependencies] section in pyproject.toml
    - TEST_DEPENDS="pytest-cov~=2.8 pytest-asyncio~=0.10 apispec[yaml,validation]~=3.1"
    - MB_ML_VER=2014
    - DOCKER_TEST_IMAGE=multibuild/xenial_x86_64

language: python
python: 3.7
os: linux
dist: xenial
services: docker

jobs:
  - os: linux
    env:
      - MB_PYTHON_VERSION=3.7
  - os: linux
    env:
      - MB_PYTHON_VERSION=3.8
  - os: osx
    language: objective-c
    env:
      - MB_PYTHON_VERSION=3.7
  - os: osx
    language: objective-c
    env:
      - MB_PYTHON_VERSION=3.8

before_install:
  - source multibuild/common_utils.sh
  - source multibuild/travis_steps.sh
  - before_install

install:
  # get and clean source
  - clean_code $REPO_DIR $BUILD_COMMIT
  - build_wheel $REPO_DIR

script:
  - install_run

after_success:
  # PYPI_TOKEN is a secure variable set via the travis-ci.com website
  - |
    if [[ $TRAVIS_PULL_REQUEST == "false" ]]; then
      python3 -m pip install twine
      python3 -m twine upload --skip-existing -u __token__ -p "$PYPI_TOKEN" ${TRAVIS_BUILD_DIR}/wheelhouse/*.whl
    else
      echo "This build is connected to a pull request. Not uploading to PyPI."
    fi
